doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Catalog:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Catalog/Domain/Entity'
                prefix: 'App\Catalog\Domain\Entity'
                alias: Catalog
            Identity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Identity/Domain/Entity'
                prefix: 'App\Identity\Domain\Entity'
                alias: Identity

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test'
